### ISSUE TITLE
[ARRT Problem] Could not upload the ConversionSettings.json

### ISSUE THREAD

**Issue by pas98** [Azure/azure-remote-rendering-asset-tool#112] opened 2022-01-14 13:24 UTC
![azure](https://user-images.githubusercontent.com/97740911/149521387-4c848af0-06ab-4771-b179-1fa05bd52284.png)

![azure2](https://user-images.githubusercontent.com/97740911/149522074-63bd4d4b-f09a-433a-9a0b-6c4eaacf1e69.png)

Hi! I'm trying to convert a FBX file into arrasset, the problem is that when I start converting the FBX with the ARRT it gives the error you can see in the screenshot. The storage account is connected, I see the files in the blob container but I can't convert anything. I've never had this problem with the previous release of ARRT. Maybe I'm doing something wrong?

**Comment by jakrams** [comment] 2022-01-14 16:51
Yes, I am able to reproduce this issue. This seems to happen when the source file is located directly in the root of the storage container, rather than a sub-folder.

Please create a sub-folder, put your FBX file there and then try again. And then let me know if the error persists.

I'll look into why exactly this happens soon.

**Comment by pas98** [comment] 2022-01-17 08:31
I tried the solution you provided, now the conversion starts but it stops immediately.
I tried to use different folders and containers for input and output but nothing changes.
![arr234](https://user-images.githubusercontent.com/97740911/149734286-ab2d37ac-d797-47dc-a43d-2c483d5c1695.png)
.

**Comment by jakrams** [comment] 2022-01-17 08:54
Hm, sorry about that. I'm wondering whether it is because of the whitespace in your file's name. I'll check that.
Btw. when a conversion fails, it should show some error message beneath the "Show advanced options" checkbox, unfortunately if it fails right away, that field doesn't immediately update (a small bug I discovered recently). You can switch back and forth between your conversion and "new conversion" to force it to update. Maybe it shows something useful then.

If this is blocking your work, please fall back to an older version of ARRT in the mean time.

**Comment by pas98** [comment] 2022-01-17 15:48
Ok, I'll use an  older version. I also tried to remove the whitespaces in the file's name but nothing changed.

**Comment by jakrams** [comment] 2022-01-17 17:42
@pas98 I have published a pre-release with a couple of fixes here:
https://github.com/Azure/azure-remote-rendering-asset-tool/releases/tag/v2.2.0

It does fix the issue that you needed to convert from a sub-folder. I am also investigating why your conversion might fail right away, but so far have no good idea. Therefore when you run a new conversion, it now prints some of the internal data to the "Log" page.

It would be great, if you could try again with this version. When it fails, please have a look at the "Log" page and post a screenshot. Please don't post it unaltered, though, as it contains sensitive information, e.g. SAS tokens that could allow people to access your storage account. Instead, please black out at least a part of the SAS token so that it is unusable. For example like this:

![image](https://user-images.githubusercontent.com/36191331/149816124-b3eed006-be7a-4b56-923f-811ce2af49d8.png)

I hope we can get to the bottom of the problem, the code in the older Arrt version isn't that different, it must be some minor issue.

**Comment by jakrams** [comment] 2022-01-21 16:51
@pas98 would be great, if you could give it another try.

**Comment by pas98** [comment] 2022-01-21 18:28
Sorry, I missed the email, tomorrow when I get to the office I’ll give it a try!

**Comment by pas98** [comment] 2022-01-24 14:01
This is what I get when the conversion fails after starting it
![arr12](https://user-images.githubusercontent.com/97740911/150796729-8eb2c1e1-3950-4451-bba0-0bcca1224705.png)

**Comment by jakrams** [comment] 2022-01-24 14:10
Thanks a lot, that looks very interesting! There are double slashes in the paths (e.g. "windows.net//solar") which is most certainly going to make problems. I'll look into why this could happen and provide you a new version soon.

**Comment by jakrams** [comment] 2022-01-24 14:31
Ok, found the issue. You must have input the "Blob Endpoint" with a trailing slash, whereas I never did that during testing:

![image](https://user-images.githubusercontent.com/36191331/150801814-18d5d0b7-e175-4d09-ab04-17642b4c0dc4.png)

This creates double slashes in the paths which makes the conversions fail like this.
I will submit a fix soon, but in the mean time you can make it work by just removing the slash.

**Comment by pas98** [comment] 2022-01-24 14:41
Perfect, now it works! Thank you!!

**Comment by jakrams** [comment] 2022-01-24 16:27
@pas98 we've published [release 2.2.0](https://github.com/Azure/azure-remote-rendering-asset-tool/releases) which includes a fix for this problem.

Thanks a lot for the help! Don't hesitate to reach out, if you find more bugs :)

**Closed by jakrams** 2022-01-24 16:27 UTC
Labels: bug
