### ISSUE TITLE
[ARRT Problem] The session is not connecting.

### ISSUE THREAD

**Issue by XcessPak** [Azure/azure-remote-rendering-asset-tool#137] opened 2022-07-14 18:59 UTC
Everything works conversion works but session is not connecting.
![Capture](https://user-images.githubusercontent.com/109309692/179061954-8991a7f1-6ccd-48db-8f92-2b6abdac89de.PNG)

**Comment by jumeder** [comment] 2022-07-15 12:10
Hi @XcessPak, most likely the ARR network traffic is blocked by your firewall and/or router settings. Can you make sure the following ip/port ranges are allowed for TCP and UDP traffic: https://docs.microsoft.com/en-us/azure/remote-rendering/overview/system-requirements#network-firewall

**Comment by jakrams** [comment] 2022-07-25 11:38
Closing this issue. Please reopen, if the problem persists.

**Comment by XcessPak** [comment] 2022-07-25 11:56
Problem persists 

Kind Regards,
[Uzair Saeed]
Chief Executive Officer
XcessPak
Suite#201, Safiya Chambers. 19-A Abbot Road Lahore.
Cell: 0322-4680661, 042-36360999
Email: ***@***.***, ***@***.***

**Comment by jakrams** [comment] 2022-07-25 11:58
Did you investigate your firewall settings, as mentioned above? This kind of issue is quite common and it's usually due to firewalls.

**Comment by XcessPak** [comment] 2022-07-25 12:06
Yes i have sir

Kind Regards,
[Uzair Saeed]
Chief Executive Officer
XcessPak
Suite#201, Safiya Chambers. 19-A Abbot Road Lahore.
Cell: 0322-4680661, 042-36360999
Email: ***@***.***, ***@***.***

**Comment by jakrams** [comment] 2022-07-25 12:13
Looking at the telemetry for your session, we see that we get a connection request, but then no UDP packages arrive from your side.

Could you please double check that the necessary ports are allowed **for UDP traffic** (this is separate from TCP).

**Comment by XcessPak** [comment] 2022-07-25 13:42
i have opnened the necessary port i.e 8266 on udp but problem persists.

**Comment by XcessPak** [comment] 2022-07-25 14:21
[XCESSPAK-MAIN.07-25-2022.19-17-14.etl.zip](https://github.com/Azure/azure-remote-rendering-asset-tool/files/9181956/XCESSPAK-MAIN.07-25-2022.19-17-14.etl.zip)
Please find attached WPA File

**Comment by XcessPak** [comment] 2022-08-01 00:37
i have opened all the necessary ports for latest version but the problem still remains.

**Comment by jakrams** [comment] 2022-08-01 12:29
These ports must be allowed to pass through not only on your PC, but also by all routers in your network. We have seen this issue many times before, and it was always some policy in the network that blocked this traffic. Especially in corporate environments router configurations are usually quite strict. As I mentioned above, we have looked at the telemetry for your session, and we don't see any UDP package arriving from your side.

**Comment by jakrams** [comment] 2022-08-01 13:50
@XcessPak could you create another ETL trace, and record it over a longer duration? From what I see, you started the connection, and stopped it after roughly 5 seconds. ARR sessions usually take longer than that to boot up. To have more information to diagnose the issue, I would need a trace that covers the entire duration from the start until the "timeout reached" error message appears.

**Comment by XcessPak** [comment] 2022-08-01 18:09
@jakrams here you go
[XCESSPAK-MAIN.08-01-2022.23-06-29.etl.zip](https://github.com/Azure/azure-remote-rendering-asset-tool/files/9236182/XCESSPAK-MAIN.08-01-2022.23-06-29.etl.zip)
.

**Comment by XcessPak** [comment] 2022-08-01 18:09
we have only one router after computer on which we have also opened the ports.

**Comment by jakrams** [comment] 2022-08-02 09:30
I'm trying to have a look at the trace, but WPA has trouble opening it:

![image](https://user-images.githubusercontent.com/36191331/182339970-7d0f6f9d-af4d-4fd3-823c-f5fa37d81c7d.png)

Opening it with the mentioned /tti option also fails. It's possible that the file got corrupted at some point.

Could you do another recording and make sure that the file can be opened with [Windows Performance Analyzer](https://docs.microsoft.com/en-us/windows-hardware/test/wpt/windows-performance-analyzer)? Since the first trace could be opened correctly, it should generally work.

Sorry for the inconvenience.

Oh and another question: Have you tried the [Unity Quickstart app](https://docs.microsoft.com/en-us/azure/remote-rendering/quickstarts/render-model) ? It uses a completely different implementation for the connection logic. If that also fails, we can be certain that it is a general problem. If that works, though, we are certain that it is a bug in ARRT. That would help us a lot to diagnose the root cause.

**Comment by jakrams** [comment] 2022-08-02 09:58
Makes sense. The storage and general connection to the ARR service mostly go through REST calls (HTTP) and regular TCP connections. Only once you start to connect to a rendering VM, we need to use UDP packages for the real-time video stream. At the moment I am very much convinced that it is an issue with your network configuration.

Please double and triple-check:

The full range of ports from 49152 to 65534 have to be open for outgoing (and best also for incoming) TCP and UDP traffic everywhere in your network:

* in your Windows Firewall
* in any additional virus scanners that may come with their own firewall
* in your office's WIFI router configuration
* in any secondary router that you may have in between
* and even by your ISP (very unlikely that this is blocked, though, and hard to check)

Also make sure that your firewall doesn't block any IP range that might be vital. See [this table](https://docs.microsoft.com/azure/remote-rendering/overview/system-requirements#network-firewall). So for example, if you want to connect to West US the IP address range 20.51.9.64/28 also must be open.

A trace can often tell us whether there is such an issue (or something else), but of course it doesn't tell us where along the route packages are blocked.

**Comment by jumeder** [comment] 2022-08-22 12:19
Closing due to inactivity - Please reopen as required.

**Comment by XcessPak** [comment] 2022-10-11 08:30
I have also opened these ports

Kind Regards,
[Uzair Saeed]
Chief Executive Officer
XcessPak
Suite#201, Safiya Chambers. 19-A Abbot Road Lahore.
Cell: 0322-4680661, 042-36360999
Email: ***@***.***, ***@***.***

**Comment by XcessPak** [comment] 2022-10-11 09:18
Yes i have opened all the ports and checked it but still not working

Kind Regards,
[Uzair Saeed]
Chief Executive Officer
XcessPak
Suite#201, Safiya Chambers. 19-A Abbot Road Lahore.
Cell: 0322-4680661, 042-36360999
Email: ***@***.***, ***@***.***

**Comment by jakrams** [comment] 2022-10-14 09:49
@XcessPak we can have another look at the telemetry, maybe we see something that we missed last time.

Could you please:

1. Start a [client trace](https://learn.microsoft.com/en-us/azure/remote-rendering/how-tos/performance-tracing)
2. Start a new session.
3. Wait for ARRT to report that it couldn't connect.
4. Stop the client trace.
5. And finally post the trace and the session ID here (maybe also a screenshot of ARRT's log).

Thanks.

**Closed** 2022-11-14 09:29 UTC
Labels: bug
